language: bash

services:
  - mysql
  - postgresql

before_script:
  - mysql -e "CREATE DATABASE dogfish_test;"
  - createdb dogfish_test
  - touch .dogfish-test-warning-given

script: ./dogfish_test

env:
  - PGDATABASE=dogfish_test
